import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const repoDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

test("frontend selectors and stylesheet structure stay valid", async () => {
  const [html, app, styles, server, storage] = await Promise.all([
    readFile(path.join(repoDir, "public", "index.html"), "utf8"),
    readFile(path.join(repoDir, "public", "app.js"), "utf8"),
    readFile(path.join(repoDir, "public", "styles.css"), "utf8"),
    readFile(path.join(repoDir, "server.js"), "utf8"),
    readFile(path.join(repoDir, "storage.js"), "utf8")
  ]);

  const selectorIds = [...app.matchAll(/querySelector\("#([A-Za-z][\w-]*)"\)/g)].map((match) => match[1]);
  for (const id of selectorIds) {
    assert.match(html, new RegExp(`id=["']${id}["']`), `Missing HTML element for #${id}`);
  }

  let braceDepth = 0;
  for (const character of styles) {
    if (character === "{") braceDepth += 1;
    if (character === "}") braceDepth -= 1;
    assert.ok(braceDepth >= 0, "Stylesheet has an unexpected closing brace.");
  }
  assert.equal(braceDepth, 0, "Stylesheet has an unclosed block.");

  assert.match(html, /<title>Apex Analytic<\/title>/);
  assert.match(html, /class="orbCore"><b>A<\/b>/, "The orb must use only the Apex A mark.");
  assert.doesNotMatch(html, /<h1>APEX<\/h1>|class="productSuffix"/, "The central Apex Analytic wordmark must stay removed.");
  assert.match(html, /<form id="chatForm"[\s\S]*?id="analyzeDealBtn"[\s\S]*?<\/form>/, "Deal analysis must remain visible inside the message bar.");
  assert.match(html, /id="sessionBriefBtn"[\s\S]*?>BRIEF<\/button>/, "V5.9 needs a compact session-brief export action.");
  assert.match(html, /id="inputModeHint"[\s\S]*?class="inputModeHint"/, "V5.4 needs a compact smart-input mode chip in the command bar.");
  assert.match(html, /id="contextReadiness"[\s\S]*?aria-label="Context readiness"/, "V5.3 needs a compact context-readiness strip near the input box.");
  assert.match(html, /id="experienceLock"[\s\S]*?aria-label="Product experience lock"/, "V5.10 needs one compact product-experience lock surface.");
  assert.equal((html.match(/data-context-reset="(?:deal|profile|guidance)"/g) || []).length, 3, "Each context card needs its own reset button.");
  assert.match(html, /id="memoryPanel"[\s\S]*?PRIVATE TO YOUR ACCOUNT[\s\S]*?id="memoryList"/, "Signed-in users need a private memory review screen.");
  assert.match(html, /id="memoryCaptureEnabled"[\s\S]*?id="memoryReasoningEnabled"[\s\S]*?id="memoryModeNotice"/, "V3 memory must expose opt-in capture and reasoning controls.");
  assert.match(html, /id="memoryProfile"[\s\S]*?id="memoryProfileTitle"[\s\S]*?id="memoryProfileDetails"/, "V3.1 needs a structured investor memory profile card.");
  assert.match(html, /data-deal-field="annualAssessmentQuitRent"[\s\S]*?data-deal-field="vacancyStressMonths"/, "Deal card needs optional v1.6 stress assumption fields.");
  assert.match(html, /data-deal-field="dealSource"[\s\S]*?data-deal-field="resalePreparation"/, "Deal card needs optional v2 workflow fields.");
  assert.match(html, /data-deal-field="comparableSource"[\s\S]*?data-deal-field="comparableAdjustmentNotes"/, "Deal card needs v4.1 transaction comparable detail fields.");
  assert.match(html, /data-deal-field="rentalSource"[\s\S]*?data-deal-field="rentalAdjustmentNotes"/, "Deal card needs v4.2 achieved rental detail fields.");
  assert.match(html, /data-deal-field="bankValuationSupport"[\s\S]*?data-deal-field="financingNotes"/, "Deal card needs v4.3 financing and valuation fields.");
  assert.match(html, /data-deal-field="supplyRadius"[\s\S]*?data-deal-field="supplyNotes"/, "Deal card needs v4.4 supply and absorption fields.");
  assert.match(html, /data-deal-field="siteVisitEvidence"[\s\S]*?data-deal-field="siteManagementNotes"/, "Deal card needs v4.5 site and management fields.");
  assert.match(html, /data-deal-field="legalTitleType"[\s\S]*?data-deal-field="legalTransactionNotes"/, "Deal card needs v4.6 legal and transaction fields.");
  assert.match(html, /data-profile-field="portfolioRole"[\s\S]*?data-profile-field="nextPurchaseReason"/, "Profile card needs optional v1.7 portfolio gate fields.");
  assert.match(html, /data-context-toggle="guidance"[\s\S]*?data-profile-field="experienceLevel"[\s\S]*?data-profile-field="onboardingNotes"/, "V5 needs a dedicated guidance card for answer style and onboarding context.");
  assert.match(html, /id="shortlistPanel"[\s\S]*?DEAL SHORTLIST[\s\S]*?id="shortlistList"/, "Analysed properties need an inline comparison shortlist.");
  assert.match(html, /id="shortlistSummary"[\s\S]*?id="shortlistList"/, "The shortlist needs a comparison summary before the deal cards.");
  assert.match(html, /id="billingSummary"[\s\S]*?id="billingPlanName"[\s\S]*?id="billingActions"/, "Signed-in accounts need one compact plan and usage surface.");
  assert.match(html, /id="reportsPanel"[\s\S]*?DEAL REPORTS[\s\S]*?id="reportsList"/, "Signed-in accounts need private report history.");
  assert.match(html, /id="journalPanel"[\s\S]*?DECISION JOURNAL[\s\S]*?id="journalEditor"/, "Signed-in accounts need an inline decision journal.");
  assert.match(html, /id="ownerMarketToggle"[\s\S]*?MARKET/, "The owner market console must be reachable from the account surface.");
  assert.match(html, /id="trustToggle"[\s\S]*?TRUST/, "The v6 trust boundary must be reachable from the account surface.");
  assert.match(html, /id="trustPanel"[\s\S]*?V6\.0 TRUST BOUNDARY[\s\S]*?WHAT APEX CAN AND CANNOT DO/, "The v6 trust boundary needs an inline workspace.");
  assert.match(html, /Normal users can submit chat and card context only[\s\S]*?cannot change the shared Apex knowledge base/, "The v6 trust boundary must preserve owner-controlled knowledge rules.");
  assert.match(html, /id="ownerMarketPanel"[\s\S]*?MARKET CONSOLE[\s\S]*?id="ownerMarketToken"/, "V2 needs an owner-token-gated market console.");
  assert.match(html, /id="ownerProjectForm"[\s\S]*?id="ownerObservationForm"[\s\S]*?id="ownerObservationList"/, "The market console needs project and observation entry surfaces.");
  assert.doesNotMatch(html, /ESTATELAB \/ JARVIS|<b>J<\/b>/, "Legacy visible branding must not return.");
  assert.doesNotMatch(html, />[^<]*(EstateLab|Jarvis)[^<]*</i, "Visible HTML copy must use Apex branding only.");
  assert.match(app, /function brandVisibleText[\s\S]*?EstateLab[\s\S]*?Jarvis/, "Rendered text must scrub legacy branding from retrieved knowledge.");
  assert.match(app, /return brandVisibleText\(lines\.join\("\\n"\)\)/, "Copied deal reports must scrub legacy branding too.");
  assert.match(app, /FRAMEWORK ONLY/, "Framework fallback responses need an explicit badge.");
  assert.match(app, /FRAMEWORK \+ AI/, "External reasoning responses need a model-neutral badge.");
  assert.doesNotMatch(app, /FRAMEWORK \+ DEEPSEEK|modelLabel\(/, "The frontend must not expose a specific reasoning model.");
  assert.match(app, /result\.memoryCandidate/, "The chat must surface memory candidates for review.");
  assert.match(app, /contextCoachMarkup\(intelligence\.contextCoach\)/, "Chat replies need the v5.2 next-move coach.");
  assert.match(app, /data-coach-prompt/, "V5.2 next-move prompts must be clickable from chat.");
  assert.match(app, /function renderContextReadiness[\s\S]*?data-readiness-panel/, "V5.3 must render clickable Deal, Profile, and Guidance readiness chips.");
  assert.match(app, /focusFirstMissingContextField\(panelName\)/, "V5.3 readiness chips must open the right card and focus missing context.");
  assert.match(app, /function detectInputMode[\s\S]*?compare[\s\S]*?offer[\s\S]*?checklist/, "V5.4 must detect smart input intent before send.");
  assert.match(app, /inputMode:\s*inputMode\.id/, "V5.4 must include detected input mode in chat requests.");
  assert.match(app, /function voiceSafeText[\s\S]*?Full answer is on screen/, "V5.5 must shorten spoken replies while preserving the written answer.");
  assert.match(app, /function responseFeedbackMarkup[\s\S]*?data-response-feedback/, "V5.6 needs inline response feedback controls.");
  assert.match(app, /function handleResponseFeedback[\s\S]*?writeResponseFeedback/, "V5.6 feedback controls must save recent answer-shape feedback locally.");
  assert.match(app, /responseFeedback:\s*responseFeedbackSummary\(\)/, "V5.6 must send recent answer feedback into future chat requests.");
  assert.match(server, /responseFeedback[\s\S]*?Recent answer feedback/, "V5.6 feedback must reach the server persona prompt.");
  assert.match(server, /feedbackPrefersShort[\s\S]*?feedbackPrefersWarmer[\s\S]*?feedbackPrefersEvidence/, "V5.6 server persona must translate feedback into answer-shape instructions.");
  assert.match(app, /function syncResponseFeedback[\s\S]*?\/api\/memory\/answer-style/, "V5.7 must sync answer-style feedback for signed-in users.");
  assert.match(app, /answerStyle\.feedbackCount/, "V5.7 memory settings must surface account-level answer-style learning.");
  assert.match(server, /function normalizeAnswerStyle[\s\S]*?slice\(0, 40\)/, "V5.7 must keep account answer-style memory compact.");
  assert.match(server, /POST" && url\.pathname === "\/api\/memory\/answer-style"/, "V5.7 needs a protected answer-style memory endpoint.");
  assert.match(server, /approvedAnswerStyleFeedback\(actor\.user\)/, "V5.7 stored answer style must feed future response-persona routing.");
  assert.match(storage, /"answerStyle":\{"version":1,"feedback":\[\]\}/, "V5.7 storage defaults need an empty answer-style memory profile.");
  assert.match(app, /data-response-refine/, "V5.8 needs an inline answer refinement action.");
  assert.match(app, /function responseRefinementPrompt[\s\S]*?Keep the same investment judgment[\s\S]*?Do not change the verdict/, "V5.8 refinement prompts must preserve the original investment judgment.");
  assert.match(app, /function handleResponseRefine[\s\S]*?submitQuestion\(prompt\)/, "V5.8 refinement actions must send a prepared follow-up prompt.");
  assert.match(app, /function sessionBriefText[\s\S]*?APEX ANALYTIC SESSION BRIEF[\s\S]*?latestApexBriefLines/, "V5.9 must build a portable session brief from current context and latest Apex direction.");
  assert.match(app, /function copySessionBrief[\s\S]*?writeClipboardText\(text\)/, "V5.9 session brief must use the shared clipboard fallback.");
  assert.match(app, /sessionBriefBtn\.addEventListener\("click"/, "V5.9 BRIEF action must be wired in the utility bar.");
  assert.match(app, /function renderExperienceLock[\s\S]*?V5 LOCK/, "V5.10 must render the product-experience lock surface.");
  assert.match(app, /function renderExperienceLock[\s\S]*?voiceResponsesEnabled/, "V5.10 lock must summarize voice state.");
  assert.match(app, /function renderExperienceLock[\s\S]*?readResponseFeedback/, "V5.10 lock must summarize answer-style tuning.");
  assert.match(app, /renderContextReadiness[\s\S]*?renderExperienceLock\(\)/, "V5.10 experience lock must refresh with context readiness.");
  assert.match(app, /function openTrustPanel[\s\S]*?classList\.add\("trustOpen"\)/, "V6.0 trust must open as a workspace state.");
  assert.match(app, /function closeTrustPanel[\s\S]*?classList\.remove\("trustOpen"\)/, "V6.0 trust must close as a workspace state.");
  assert.match(app, /trustToggle\.addEventListener\("click"/, "V6.0 trust action must be wired.");
  assert.match(app, /\/api\/memory\/settings/, "Memory collection and reasoning must be controlled through explicit settings.");
  assert.match(app, /captureEnabled:\s*memoryCaptureEnabled\.checked/, "Memory capture must be opt-in from the UI.");
  assert.match(app, /reasoningEnabled:\s*memoryReasoningEnabled\.checked/, "Using approved memory in reasoning must be opt-in from the UI.");
  assert.match(app, /function renderMemoryProfile/, "V3.1 must render the derived investor memory profile.");
  assert.match(app, /item\.categoryLabel/, "V3.2 memory review queue must show upgraded category labels.");
  assert.match(app, /item\.profileImpact/, "V3.2 memory review queue must explain how each memory affects the profile.");
  assert.match(app, /data-memory-action="approve"/, "Memory candidates must require explicit approval.");
  assert.match(app, /data-analysis-action="report"/, "Every structured analysis needs a printable deal report.");
  assert.match(app, /data-analysis-action="copy"/, "Every structured analysis needs a text copy export.");
  assert.match(app, /decisionFocusMarkup\(analysis\)/, "Deal reports need a single decision-focus explanation.");
  assert.match(app, /personalizedChallengeMarkup\(analysis\.personalizedChallenge\)/, "V3.3 deal reports need a separate personalized challenge card.");
  assert.match(app, /readinessMarkup\(analysis\.investorReadiness\)/, "Deal reports need an investor readiness summary.");
  assert.match(app, /productExperienceMarkup\(analysis\.productExperience\)/, "Deal reports need the v5 product-experience guidance summary.");
  assert.match(app, /evidenceChecklistMarkup\(analysis\.evidenceChecklist/, "Deal reports need an evidence checklist.");
  assert.match(app, /evidenceEngineMarkup\(analysis\.evidenceEngine\)/, "Deal reports need v4.0 evidence engine.");
  assert.match(app, /transactionComparableMarkup\(analysis\.transactionComparableEvidence\)/, "Deal reports need v4.1 transaction comparable evidence.");
  assert.match(app, /achievedRentalMarkup\(analysis\.achievedRentalEvidence\)/, "Deal reports need v4.2 achieved rental evidence.");
  assert.match(app, /financingValuationMarkup\(analysis\.financingValuationEvidence\)/, "Deal reports need v4.3 financing and valuation evidence.");
  assert.match(app, /supplyAbsorptionMarkup\(analysis\.supplyAbsorptionEvidence\)/, "Deal reports need v4.4 supply and absorption evidence.");
  assert.match(app, /siteManagementMarkup\(analysis\.siteManagementEvidence\)/, "Deal reports need v4.5 site and management evidence.");
  assert.match(app, /legalTransactionMarkup\(analysis\.legalTransactionEvidence\)/, "Deal reports need v4.6 legal and transaction evidence.");
  assert.match(app, /dueDiligenceMarkup\(analysis\.dueDiligencePlan\)/, "Deal reports need a due-diligence task pack.");
  assert.match(app, /stressEnvelopeMarkup\(analysis\.stressEnvelope\)/, "Deal reports need v1.6 stress envelope.");
  assert.match(app, /portfolioGateMarkup\(analysis\.portfolioGate\)/, "Deal reports need v1.7 portfolio expansion gate.");
  assert.match(app, /marketPulseMarkup\(analysis\.marketPulse\)/, "Deal reports need v1.8 market cycle and liquidity pulse.");
  assert.match(app, /holdExitPlanMarkup\(analysis\.holdExitPlan\)/, "Deal reports need v1.9 hold, refinance, and exit plan.");
  assert.match(app, /decisionSealMarkup\(analysis\.decisionSeal\)/, "Deal reports need v1.10 decision seal.");
  assert.match(app, /v2WorkflowMarkup\("V2\.1 SITE VISIT ASSISTANT", analysis\.siteVisitAssistant/, "Deal reports need v2.1 site visit assistant.");
  assert.match(app, /v2WorkflowMarkup\("V2\.2 SOURCING \/ PROFESSIONAL FILTER", analysis\.sourcingProfessional/, "Deal reports need v2.2 sourcing and professional filter.");
  assert.match(app, /v2WorkflowMarkup\("V2\.3 TENANT \/ RENTAL PLAN", analysis\.tenantRentalPlan/, "Deal reports need v2.3 tenant and rental plan.");
  assert.match(app, /v2WorkflowMarkup\("V2\.4 EXIT STRATEGY", analysis\.exitStrategy/, "Deal reports need v2.4 exit strategy.");
  assert.match(app, /executionPlanMarkup\(analysis\.executionPlan\)/, "Deal reports need v1.5 execution calibration.");
  assert.match(app, /learningLoopMarkup\(analysis\.learningLoop\)/, "Deal reports need visible private learning signals when available.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.4 DEAL MEMORY COMPARISON", analysis\.dealMemoryComparison/, "Deal reports need v3.4 saved deal comparison.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.5 BELIEF TRACKER", analysis\.beliefTracker/, "Deal reports need v3.5 belief tracking.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.6 SOURCE TRANSPARENCY", analysis\.sourceTransparency/, "Deal reports need v3.6 source transparency.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.7 MEMORY CONFLICTS", analysis\.memoryConflicts/, "Deal reports need v3.7 memory conflict handling.");
  assert.match(app, /v3MemoryInsightMarkup\("V3\.8 PERSONAL OPERATING RULES", analysis\.personalOperatingRules/, "Deal reports need v3.8 operating rules.");
  assert.match(app, /function shortlistRankScore/, "The shortlist must rank deals using an adjusted comparison score.");
  assert.match(app, /shortlistSummaryMarkup\(items\)/, "The shortlist must render a comparison summary.");
  assert.match(app, /recommendationBlockers: analysis\.recommendationBlockers/, "Shortlisted deals must preserve decision blockers for comparison.");
  assert.match(app, /decisionFocus: analysis\.decisionFocus/, "Shortlisted deals must preserve decision focus for comparison.");
  assert.match(app, /personalizedChallenge: analysis\.personalizedChallenge/, "Shortlisted deals must preserve V3.3 personalized challenge context.");
  assert.match(app, /productExperience: analysis\.productExperience/, "Shortlisted deals must preserve V5 product-experience context.");
  assert.match(app, /learningLoop: analysis\.learningLoop/, "Shortlisted deals must preserve learning signals for comparison.");
  assert.match(app, /evidenceEngine: analysis\.evidenceEngine/, "Shortlisted deals must preserve V4.0 evidence engine.");
  assert.match(app, /transactionComparableEvidence: analysis\.transactionComparableEvidence/, "Shortlisted deals must preserve V4.1 transaction comparable evidence.");
  assert.match(app, /achievedRentalEvidence: analysis\.achievedRentalEvidence/, "Shortlisted deals must preserve V4.2 achieved rental evidence.");
  assert.match(app, /financingValuationEvidence: analysis\.financingValuationEvidence/, "Shortlisted deals must preserve V4.3 financing and valuation evidence.");
  assert.match(app, /supplyAbsorptionEvidence: analysis\.supplyAbsorptionEvidence/, "Shortlisted deals must preserve V4.4 supply and absorption evidence.");
  assert.match(app, /siteManagementEvidence: analysis\.siteManagementEvidence/, "Shortlisted deals must preserve V4.5 site and management evidence.");
  assert.match(app, /legalTransactionEvidence: analysis\.legalTransactionEvidence/, "Shortlisted deals must preserve V4.6 legal and transaction evidence.");
  assert.match(app, /dealMemoryComparison: analysis\.dealMemoryComparison/, "Shortlisted deals must preserve V3.4 saved deal comparison.");
  assert.match(app, /beliefTracker: analysis\.beliefTracker/, "Shortlisted deals must preserve V3.5 belief tracking.");
  assert.match(app, /sourceTransparency: analysis\.sourceTransparency/, "Shortlisted deals must preserve V3.6 source transparency.");
  assert.match(app, /memoryConflicts: analysis\.memoryConflicts/, "Shortlisted deals must preserve V3.7 memory conflict handling.");
  assert.match(app, /personalOperatingRules: analysis\.personalOperatingRules/, "Shortlisted deals must preserve V3.8 operating rules.");
  assert.match(app, /analysis\.dimensions/, "Deal results must render separate decision dimensions.");
  assert.match(app, /analysis\.scenarios/, "Deal results must render downside scenarios.");
  assert.match(app, /marketIntelligenceMarkup\(analysis\.marketIntelligence\)/, "Deal results must render matched dated market intelligence.");
  assert.match(app, /type === "market"/, "Market observations need a distinct source label.");
  assert.match(app, /\/api\/billing\/status/, "The account surface must load report entitlements.");
  assert.match(app, /\/api\/reports/, "The report-history surface must use private account storage.");
  assert.match(app, /\/api\/journal/, "The decision journal must use private account storage.");
  assert.match(app, /\/api\/owner\/market\/projects/, "The v2 market console must load and create owner market projects.");
  assert.match(app, /\/api\/owner\/market\/observations/, "The v2 market console must load and create owner market observations.");
  assert.match(app, /x-estatelab-owner-token/, "Owner market writes must require the owner token header.");
  assert.match(app, /ownerMarketEnabled\s*=\s*Boolean\(status\.ownerMarket\?\.enabled\)/, "The frontend must detect whether the owner market API is enabled.");
  assert.match(app, /data-analysis-action="journal"/, "Saved reports need a direct decision-record action.");
  assert.match(app, /function resetContextCard[\s\S]*?localStorage\.removeItem\(storageKey\)/, "Card reset must clear both visible fields and saved browser context.");
  assert.match(app, /data-context-body="\$\{panelName\}"[\s\S]*?\[data-profile-field\]/, "Resetting Guidance must only clear its own visible fields while preserving the rest of the profile context.");
  assert.match(styles, /\.memoryOpen \.transcript[\s\S]*?display:\s*none;/, "The memory screen must replace chat content instead of opening a popup.");
  assert.match(styles, /\.memorySettings[\s\S]*?grid-template-columns:/, "V3 memory consent controls need a compact settings layout.");
  assert.match(styles, /\.memoryProfile[\s\S]*?\.memoryProfileDetails/, "V3.1 memory profile needs a styled summary card.");
  assert.match(styles, /\.memoryItem\.priority-high[\s\S]*?border-color/, "V3.2 high-priority memory review items need a visible warning style.");
  assert.match(styles, /\.reportsOpen \.transcript[\s\S]*?display:\s*none;/, "The report history must replace chat content instead of opening a popup.");
  assert.match(styles, /\.journalOpen \.transcript[\s\S]*?display:\s*none;/, "The decision journal must replace chat content instead of opening a popup.");
  assert.match(styles, /\.ownerMarketOpen \.transcript[\s\S]*?display:\s*none;/, "The owner market console must replace chat content instead of opening a popup.");
  assert.match(styles, /\.ownerMarketPanel[\s\S]*?\.ownerMarketWorkspace[\s\S]*?grid-template-columns:/, "The v2 market console needs a styled owner workspace.");
  assert.match(styles, /\.ownerMarketLists[\s\S]*?\.ownerObservationList[\s\S]*?overflow-y:\s*auto;/, "Market observation lists must stay scrollable.");
  assert.match(styles, /\.analysisMarketPulse[\s\S]*?overflow-wrap:\s*anywhere;/, "Market observations must remain readable without overflowing the report.");
  assert.match(styles, /\.analysisOverview[\s\S]*?grid-template-columns:/, "The v1.1 report needs an organized readiness and scorecard overview.");
  assert.match(styles, /\.analysisEvidence[\s\S]*?\.evidenceItem/, "The v1.1 report needs a styled evidence checklist.");
  assert.match(styles, /\.analysisEvidenceEngine[\s\S]*?\.evidenceGate/, "The v4.0 evidence engine needs styled evidence gates.");
  assert.match(styles, /\.analysisTransactionComps[\s\S]*?\.transactionCompCheck/, "The v4.1 comparable evidence card needs styled checks.");
  assert.match(styles, /\.analysisDiligence[\s\S]*?\.diligenceTask/, "The v1.4 report needs a styled due-diligence task pack.");
  assert.match(styles, /\.analysisStress[\s\S]*?\.stressAssumptions/, "The v1.6 report needs a styled stress envelope.");
  assert.match(styles, /\.analysisPortfolioGate[\s\S]*?\.portfolioCheck/, "The v1.7 report needs a styled portfolio expansion gate.");
  assert.match(styles, /\.analysisMarketCycle[\s\S]*?\.marketCycleCheck/, "The v1.8 report needs a styled market cycle and liquidity pulse.");
  assert.match(styles, /\.analysisHoldExit[\s\S]*?\.holdExitTrigger/, "The v1.9 report needs a styled hold, refinance, and exit plan.");
  assert.match(styles, /\.analysisDecisionSeal[\s\S]*?\.sealCondition/, "The v1.10 report needs a styled decision seal.");
  assert.match(styles, /\.analysisPersonalChallenge[\s\S]*?\.personalChallengeCheck/, "The v3.3 personalized challenge needs styled report cards.");
  assert.match(styles, /\.analysisV2Workflow[\s\S]*?\.v2WorkflowCheck/, "The v2 workflow report sections need styled checklist cards.");
  assert.match(styles, /\.analysisExecution[\s\S]*?\.executionAction/, "The v1.5 report needs a styled execution calibration pack.");
  assert.match(styles, /\.analysisLearning[\s\S]*?\.learningSignal/, "The v1.2 report needs styled memory and journal learning signals.");
  assert.match(styles, /\.analysisV3Insight[\s\S]*?\.v3InsightItem/, "The v3 memory-path report sections need styled compact cards.");
  assert.match(styles, /\.analysisProductExperience[\s\S]*?\.productExperienceCheck/, "The v5 product-experience report section needs styled compact cards.");
  assert.match(styles, /\.contextCoach[\s\S]*?data-coach-prompt|\.contextCoach[\s\S]*?\.contextCoach button/, "The v5.2 next-move coach needs styled prompt buttons.");
  assert.match(styles, /\.contextReadiness[\s\S]*?\.contextReadiness button/, "The v5.3 context-readiness strip needs styled clickable chips.");
  assert.match(styles, /\.accountOpen \.contextReadiness[\s\S]*?display:\s*none;/, "Context readiness must hide when workspace panels replace chat.");
  assert.match(styles, /\.experienceLock[\s\S]*?\.experienceLock\.thin span/, "V5.10 experience lock needs compact state styling.");
  assert.match(styles, /\.accountOpen \.experienceLock[\s\S]*?\.shortlistOpen \.experienceLock[\s\S]*?display:\s*none;/, "V5.10 experience lock must hide when workspace panels replace chat.");
  assert.match(styles, /\.trustOpen \.transcript[\s\S]*?display:\s*none;/, "The v6 trust boundary must replace chat content instead of opening a popup.");
  assert.match(styles, /\.trustPanel[\s\S]*?\.trustGrid[\s\S]*?grid-template-columns:/, "The v6 trust boundary needs a compact organized layout.");
  assert.match(styles, /\.inputModeHint[\s\S]*?\.commandBar\[data-input-mode="voice"\]/, "V5.4 smart input mode needs styled command-bar states.");
  assert.match(styles, /\.voiceMuted[\s\S]*?#soundToggle/, "V5.5 needs a visible muted-voice state.");
  assert.match(styles, /\.responseFeedback[\s\S]*?button\.active/, "V5.6 response feedback controls need compact active-state styling.");
  assert.match(styles, /\.responseFeedback \[data-response-refine\][\s\S]*?display:\s*none;/, "V5.8 refinement action needs compact styling and a hidden state.");
  assert.match(styles, /\.shortlistCompare[\s\S]*?adjusted|\.shortlistCompare[\s\S]*?grid-template-columns:/, "The v1.3 shortlist needs a styled comparison summary.");
  assert.match(styles, /\.shortlistItem\.blocked[\s\S]*?border-color/, "Blocked shortlist items need a visible comparison warning state.");

  assert.match(styles, /\.conversation:has\(\.contextPanel\.expanded\) \.transcript[\s\S]*?display:\s*none;/, "Expanded cards must replace the transcript instead of overflowing beneath it.");
  assert.match(styles, /\.contextHeader[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\) auto;/, "Card reset controls must fit beside the expandable header.");
  assert.match(styles, /\.contextPanel\.expanded \.contextGrid[\s\S]*?overflow-y:\s*auto|\.contextGrid[\s\S]*?overflow-y:\s*auto/, "Expanded card fields must remain scrollable.");
  assert.match(styles, /max-height:\s*calc\(100dvh - 260px\)/, "Mobile expanded cards need a viewport-bound field area.");
  assert.match(styles, /\.identity #assistantPrompt[\s\S]*?text-align:\s*center;/, "The ready prompt must remain centered beneath the orb on mobile.");
  assert.match(styles, /\.sourceSummary p[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/, "Mobile source details must stack instead of squeezing text into columns.");
  assert.match(styles, /\.cornerBottomLeft[\s\S]*?bottom:\s*max\(4px, env\(safe-area-inset-bottom\)\);[\s\S]*?left:\s*10px;/, "The mobile HUD frame must sit outside the bottom controls.");
  assert.match(styles, /\.conversation[\s\S]*?bottom:\s*max\(24px, calc\(env\(safe-area-inset-bottom\) \+ 16px\)\);/, "Mobile controls need clearance above the HUD frame.");
});
